# Generated by Django 3.1.7 on 2021-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('sub_project', models.CharField(max_length=100)),
                ('planned_hours', models.FloatField()),
                ('consumed_hours', models.FloatField()),
                ('consumed_hours_p', models.FloatField()),
                ('total_task', models.IntegerField()),
                ('done_task', models.IntegerField()),
                ('done_task_p', models.FloatField()),
            ],
        ),
    ]
