# Generated by Django 3.1.7 on 2021-03-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sub_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hp',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hp',
            name='sub_project',
        ),
        migrations.AddField(
            model_name='hp',
            name='project_hp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='charts.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hp',
            name='sub_project_hp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_project', to='charts.sub_projects'),
            preserve_default=False,
        ),
    ]
